[package]
name = "fates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.1"
sqlx = { version = "0.5", features = [ "runtime-actix-native-tls" , "postgres" ] }
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
num_enum = "0.5.6"
str_inflector = "0.12.0"
actix-cors = "0.6.0-beta.8"
redis = { version = "0.17.0", features = ["tokio-comp"] }
